# Generated by Django 5.1.7 on 2025-07-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('WEBSITE', 'Website'), ('SOCIAL MEDIA', 'Social Media'), ('MARKETING', 'Marketing'), ('APP', 'App')], max_length=50)),
                ('image', models.ImageField(upload_to='project_images/')),
                ('link', models.URLField()),
            ],
        ),
    ]
